name: Sync branch

on:
  push:
    branches:
      - main

jobs:
  sync-branch:
    name: Update v1 branch
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # Only run on original repository
    if: github.repository == 'lamkotien/cloudflare-gateway-pihole-scripts'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: main
      - uses: connor-baer/action-sync-branch@v2.0.1
        with:
          branch: main
          token: ${{ secrets.GITHUB_TOKEN }}
          # Force push is enabled since v1 is supposed to be an exact copy of main until breaking changes are made
          force: true
